apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: sea-bank-demo
  labels:
    app.kubernetes.io/name: sea-bank-demo
    app.kubernetes.io/component: auth-service
    app.kubernetes.io/part-of: sea-bank-demo
spec:
  selector:
    app.kubernetes.io/component: auth-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
