apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: sea-bank-demo
  labels:
    app.kubernetes.io/name: sea-bank-demo
    app.kubernetes.io/component: account-service
    app.kubernetes.io/part-of: sea-bank-demo
spec:
  selector:
    app.kubernetes.io/component: account-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  type: ClusterIP
