apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-service
  namespace: sea-bank-demo
  labels:
    app.kubernetes.io/name: sea-bank-demo
    app.kubernetes.io/component: transfer-service
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/part-of: sea-bank-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: transfer-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sea-bank-demo
        app.kubernetes.io/component: transfer-service
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/part-of: sea-bank-demo
    spec:
      containers:
        - name: transfer-service
          image: localhost/sea-bank-demo/transfer-service:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: sea-bank-demo-config
          env:
            - name: SERVICE_NAME
              value: "transfer-service"
            - name: PORT
              value: "8083"
            - name: ACCOUNT_URL
              value: "http://account-service:8082"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: sea-bank-mysql
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sea-bank-mysql
                  key: password
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          startupProbe:
            httpGet:
              path: /healthz
              port: 8083
            periodSeconds: 3
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
